[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn api_server:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
